### ISSUE TITLE
memory size for 256 ?

### ISSUE THREAD

**Issue by andorxornot** [HelenMao/SAVI2I#2]
I like your results. 
but why does this network need so much memory, even for size 256?
i can't use my 1080ti with 11gb

**Comment by HelenMao** [comment]
Hi, thanks for your attention to our work.
Yes, as mentioned in the readme.md, we suggest using memory > 16G to run the model (2 GPUs of P100 or 32 GB V100). That is because we translate the image into the target domain by using the referenced attribute vectors, the signed attribute vectors, and its sign-symmetrical attribute vectors. In addition, we also adopt interpolated images using interpolated attribute vectors. Both the forward operation and discriminator optimization needs these images, which takes up a lot of memory.
I have tried optimizing the memory of the model, however, the training speed becomes very slow.
I will try [apex](https://github.com/NVIDIA/apex) in the future to see whether it will reduce much memory or not.
